### ISSUE TITLE
bug: disable hide autoplay button crash

### ISSUE THREAD

**Issue by uvzen** [revanced/revanced-patches#263]
### Type

Other

### Bug description

When I disable the option to hide the autoplay button and when I run the video and click anywhere on the yt application screen, it crashes. I used the latest patches that were released 30 minutes ago. Revanced-cli, patches and integrations I used the latest versions.

### Steps to reproduce

1. disable hiding autoplay button in revanced settings> layout settings> select the autoplay button to make it blue
2. turn on some video
3. click on the video being played to try to pause it or change the quality
4. youtube app should crash

### Relevant log output

```shell
none
```

### Solution

Don't use the autoplay button until this is fixed

**Comment by TheJeterLP** [comment]
Can you provide an adb logcat for the crash?

**Comment by uvzen** [comment]
> Can you provide an adb logcat for the crash?
Should I just run the adb logcat command and copy everything?

**Comment by TheJeterLP** [comment]
> > Can you provide an adb logcat for the crash?
> 
> Should I just run the adb logcat command and copy everything?
> 

Look at the readme of revanced-integrations on GitHub for how to get a proper logcat

**Comment by uvzen** [comment]
> > > Can you provide an adb logcat for the crash?
> > 
> > 
> > Should I just run the adb logcat command and copy everything?
> 
> Look at the readme of revanced-integrations on GitHub for how to get a proper logcat


Here are the logs.
[log.txt](https://github.com/revanced/revanced-patches/files/9229609/log.txt)

**Comment by TheJeterLP** [comment]
> > > > Can you provide an adb logcat for the crash?
> > > 
> > > 
> > > Should I just run the adb logcat command and copy everything?
> > 
> > Look at the readme of revanced-integrations on GitHub for how to get a proper logcat
> 
> 
> Here are the logs.
> [log.txt](https://github.com/revanced/revanced-patches/files/9229609/log.txt)
> 

Okay so most of these issues have been fixed already. Could you rebuild and try again?

**Comment by uvzen** [comment]
Still the same, here a logs from a moment ago.
[log.txt](https://github.com/revanced/revanced-patches/files/9229660/log.txt)

**Comment by EatVanced** [comment]
revanced-cli-2.8.0-all.jar
revanced-patches-2.28.1.jar
Still crash
[logcat_08-01-2022_13-55-33.txt](https://github.com/revanced/revanced-patches/files/9231628/logcat_08-01-2022_13-55-33.txt)

**Comment by DerivativeOfLog7** [comment]
I can confirm I'm having the same issue
Root, microg-support excluded, enable-debugging included
YouTube 17.29.34
RV CLI 2.8.1
RV Patches 2.28.2
RV Integrations 0.30.4
[log.txt](https://github.com/revanced/revanced-patches/files/9241004/log.txt)

**Comment by PalmDevs** [comment]
Can reproduce.

See mentioned issue above, it was a duplicate but it has logs.

**Comment by Crescendo-BLYAT** [comment]
this needs to use **-e hide-autoplay-button** in the command line during patching for workaround....

**Comment by AMSAMSAMSAMS** [comment]
> this needs to use **-e hide-autoplay-button** in the command line during patching for workaround.... after explicitly excluding those switch, the toggle in layout is working perfectly....

Confirmed this workaround works! Thanks....

**Comment by oSumAtrIX** [comment]
IIrc if you just delete the cache it should be fixed. A recent change was made to the settings, hence the error.

**Comment by TheJeterLP** [comment]
> IIrc if you just delete the cache it should be fixed. A recent change was made to the settings, hence the error. Please confirm if it works and close the issue.

Wrong. That error you mean was already fixed. This is a different one.

**Comment by DerivativeOfLog7** [comment]
> IIrc if you just delete the cache it should be fixed. A recent change was made to the settings, hence the error. Please confirm if it works and close the issue.

Nope
