### ISSUE TITLE
bug(YouTube): Watch history does not work

### ISSUE THREAD

**Issue by Laenthor12** [ReVanced/revanced-patches#2779]
### Bug description

Revanced history not being updated and only shows Shorts (no regular videos). This does not happen on desktop nor the official app.

## Solution

The problem is fixed.

Commit bcd8b48e70693dac1bfcc0bf4971d6b526065b59 solves the issue.

Repatch as usual to get the fix.

**NOTE**:  This fix will _not_ restore the watch history of videos viewed before March 2024.  Your old watch history can be viewed at https://myactivity.google.com/product/youtube but there is no fix to restore your prior history inside the YT app.

If you are still experiencing problems, then uninstall everything (ReVanced Manager, ReVanced YouTube, MicroG) and start over.

If new videos are still not showing up in your history, then also turn off other adblock apps if present (such as DNS ad blockers), and make sure your [watch history controls](https://myactivity.google.com/product/youtube/controls) are not paused or disabled. If all this still fails then try using a different YT account.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by JeremyLaurent** [comment]
Having the exact same issue currently

**Comment by mcfisch** [comment]
I can confirm that with YT Premium disabling the spoofing made the history working again after the required restart.

**Comment by StuntHacks** [comment]
> I can confirm that with YT Premium disabling the spoofing made the history working again after the required restart.

Any way of still having playback work reliably without spoofing? If I turn it off I have the issue of not being able to play videos for longer than a minute again

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios 
I'd not be surprised if that has an effect on recommendations as well. One way to make it show up would be to make unspoofed requests at first, then, spoofed ones, but this would only fix the watch history updating. YouTube may probably treat the spoofed ones as unwatched and so the recommendations would be affected again.

**Comment by oSumAtrIX** [comment]
Looks like on https://myactivity.google.com/product/youtube they are still being tracked.

**Comment by Cico90** [comment]
So! What is the solution to this?

**Comment by Felina-Lain** [comment]
Hi, could anyone tell me which category is the app spoofing parameter in? It's kinda hard for me to locate it because Revanced menu is in another language, so the option probably is too, and I can't find it, but with the category I might?

**Comment by oSumAtrIX** [comment]
PoC fix:

https://github.com/ReVanced/revanced-patches/commit/e19e64639f4073aed7862192de1a0ca6277b5ae5
https://github.com/ReVanced/revanced-integrations/commit/ee3c5e5211940228f841c19d0ddcd5c411922b70

This seems to work and could deprecate all the other fixes we have for spoofing the client, such as Storyboard or the parameter. This approach spoofs the client to an IOS device. Requests made on IOS seem unaffected by playback issues.

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios I have force pushed a new implementation to the same branches.

Some small issues are left, such as making the request using the custom player parameters and fixing the request's failure. Curl works:
https://github.com/ReVanced/revanced-integrations/blob/106f6c78f8539474106af9a7110043e3447e7011/app/src/main/java/app/revanced/integrations/youtube/patches/spoof/SpoofSignaturePatch.java#L109

To implement params this can be used as a reference:
https://github.com/LuanRT/YouTube.js/blob/7ca2a0c3e43ebd4b9443e69b7432f302b09e9c7a/src/core/endpoints/PlayerEndpoint.ts#L46

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios https://github.com/ReVanced/revanced-integrations/blob/a4a923e0abb889c324c3603509bc0d87da676a68/app/src/main/java/app/revanced/integrations/youtube/patches/spoof/SpoofSignaturePatch.java#L70 Whats the reason for having a map for every video id?

We could simply overwrite the current map with a new one as there is ever only one video playing.

**Comment by oSumAtrIX** [comment]
Every time a video is loaded, a player response model is constructed. But YouTube may be reusing a request or protobuf response.

**Comment by oSumAtrIX** [comment]
So, with the current pushed code, the issue is partially resolved. Videos load and are also added to watch history. The only issue is, that the playback stops just like before, but after what looks like a timeout, continues to load.

Inspecting the network shows that changing the URL had no effect until the video stopped and began to buffer. Once the video stopped and the timeout elapsed, the available qualities are only 320p and 720p.

Currently, the FormatStreamModel constructor is hooked so that every instance that may be created anywhere is handled, but it may be the case that the URL field is overwritten at a later point after we do it.

The object that is passed down to the constructor stores the URL which FormatStreamModel sets to a field, but we also hook the field of that object:

<img width="795" alt="image" src="https://github.com/ReVanced/revanced-patches/assets/13122796/c763f5b8-6937-447f-82cb-a55db532b95e">

So either something that set that field in that object, is being used somewhere else, or the value is overwritten somehow.

**Comment by oSumAtrIX** [comment]
Fixed with bcd8b48e70693dac1bfcc0bf4971d6b526065b59. If anyone can, please test it.

**Comment by ILoveOpenSourceApplications** [comment]
Since we changed the spoofing method, is there any changes to the side effects due to spoofing then vs now or are they still the same?

**Comment by oSumAtrIX** [comment]
Nothing changed in this regard.

**Comment by Ak73b** [comment]
will the issue get fixed? Soon hopefully? Should I expect it to be fixed?

**Comment by TechGamerExpert** [comment]
Will we have to re-up date for this changes?

**Comment by RebelliousX** [comment]
@LisoUseInAIKyrios How to test then? Repatching apk with v4.2.0 again?

**Comment by exzhawk** [comment]
I can confirm this is working. using 4.3.0-dev.11

**Comment by mityukov** [comment]
4.3.0? What is this? My YouTube revanced is 19.04...

**Comment by ILoveOpenSourceApplications** [comment]
Those who are using ReVanced Manager won't be able to use this as it's still in the dev branch. While those using ReVanced CLI and a PC/Laptop to patch their apk can test it right now.

**Comment by sliceanddice9** [comment]
> Those who are using ReVanced Manager won't be able to use this as it's still in the dev branch. While those using ReVanced CLI and a PC/Laptop to patch their apk can test it right now.
> 
> Edit: ReVanced Manager users will have to wait till it's merged to the main branch.

Not to rush any of the developers (who we are all very appreciative of for dissecting this issue), but is there a ETA for when it will be merged to the main branch for ReVanced Manager?

**Comment by RebelliousX** [comment]
You would think if someone is using the dev pre-released APK of the manager, he / she would be using the nightly-dev releases of the patches by default, but no.

Meh, bad design.

**Comment by AVAtarMod** [comment]
> You would think if someone is using the dev pre-released APK of the manager, he / she would be using the nightly-dev releases of the patches by default, but no.
> 
> Meh, bad design.

You are free to open issue and write pull request in the [https://github.com/ReVanced/revanced-manager](revanced-manager) repository which implement this feature. Don't push developers

**Comment by Ushie** [comment]
1-72h

> > Those who are using ReVanced Manager won't be able to use this as it's still in the dev branch. While those using ReVanced CLI and a PC/Laptop to patch their apk can test it right now.
> > Edit: ReVanced Manager users will have to wait till it's merged to the main branch.
> 
> Not to rush any of the developers (who we are all very appreciative of for dissecting this issue), but is there a ETA for when it will be merged to the main branch for ReVanced Manager?

1-72h

**Comment by RebelliousX** [comment]
My apologies, I didn't mean any disrespect, it is the way I criticize things..

**Comment by Ak73b** [comment]
> Those who are using ReVanced Manager won't be able to use this as it's still in the dev branch. While those using ReVanced CLI and a PC/Laptop or Termux on their phone to patch their apk can test it right now.
> 
> Edit: ReVanced Manager users will have to wait till it's merged to the main branch.

Do you get all your history that went missing back or just new history tracks now going forward?

**Comment by Ushie** [comment]
Going forward

**Comment by OverLordOfYou007** [comment]
Will this be a push notification through Revance once done?

**Comment by malaguer** [comment]
> > Those who are using ReVanced Manager won't be able to use this as it's still in the dev branch. While those using ReVanced CLI and a PC/Laptop or Termux on their phone to patch their apk can test it right now.
> > Edit: ReVanced Manager users will have to wait till it's merged to the main branch.
> 
> Do you get all your history that went missing back or just new history tracks now going forward?

History missing videos are still missing, although you can recover them from myactivity.google.com .
New watched videos are correctly stored in History section.

**Comment by TobySkarting** [comment]
> Fixed with [bcd8b48](https://github.com/ReVanced/revanced-patches/commit/bcd8b48e70693dac1bfcc0bf4971d6b526065b59). If anyone can, please test it.
> 
> @LisoUseInAIKyrios, on a related note, spoofing the video URLs may be something we might keep an eye on as it would eliminate the need for the workarounds.

It works.
Payloads I use: `java -jar .\revanced-cli-4.4.1-dev.1-all.jar patch --options .\optaions.json -b .\revanced-patches-4.3.0-dev.13.jar -m .\revanced-integrations-1.4.0-dev.9.apk '.\com.google.android.youtube_19.04.37-1544154560_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk'`

**Comment by j0hnnycache** [comment]
> If you have YT premium then you might be able to turn off signature spoofing and experience no issues playing videos more than 1 minute.

I have premium and tested this, didn't work for me. Buffering started after a short time watching.

**Comment by j0hnnycache** [comment]
> 
> 1-72h
Damn, that was quick!

**Comment by TheobaldLeonhart** [comment]
I would try the Dev version, but I only really know how to use ADB to uninstall bloatware. And even then, I tend to mess something up
So I'll just wait, until the Manager gets this fix

**Comment by j0hnnycache** [comment]
> It still fails for some premium users. That's why it's 'might be able'

Very odd. Thanks Google, I guess? 😁

I'm excited for this patch, using the main YT app is such a huge step backwards. Thank you to all the devs of this awesome app!

**Comment by YT-Advanced** [comment]
@oSumAtrIX The workaround seem to make the video link with timestamp buffering.
Example: https://youtu.be/nlarIgSvV_U?t=1
However, the hook position that I sent you before may helpful xD

**Comment by Qunas101** [comment]
For anyone who had to subject themselves to the default YT app, you can just use Firefox with uBlock add-on. May not be as nice and snappy, but it works for the time being

**Comment by ib321** [comment]
First of all i would like to thankyou all the developers of this Team for their work toward this awesome project.
And Yes I am also facing same issue with watch history not being recorded if the spoof is on and if spoof is off then playback issue.
I thought to report this to developers but then i came across this thread and now happy to know that it's fixed will wait for the release.... ✌️🕊️

**Comment by 0xrxL** [comment]
Mhh...nope. This workaround doesn't work for me. I tested it with a free account and a video without timestamp. 🤷‍♂️

**Comment by 0xrxL** [comment]
Mhh...nope. This workaround doesn't work for me (I'm facing buffering issue). I tested it with a free account and a video without timestamp. 🤷‍♂️

P.S: Obviously the history is working again.

**Comment by YT-Advanced** [comment]
Wao, long time not seeing you there.

> I tested it with a free account and a video without timestamp. 🤷‍♂️

You mean open the video link from another app?

**Comment by 0xrxL** [comment]
> Wao, long time not seeing you there.
> 
> > I tested it with a free account and a video without timestamp. 🤷‍♂️
> 
> You mean open the video link from another app?

Nope. I mean if I open a video from revanced homepage (or watching later playlist), it stuck on buffering circular loading after some minutes.

So this workaround solved the history problem, but (at least for me) broke the playback buffering.

**Comment by 0xrxL** [comment]
> Wao, long time not seeing you there.

P.S: Yes, sometimes I take a look at the repository, in case there is a new interesting patch. Unfortunately I also had this history problem.

**Comment by 0xrxL** [comment]
> @0xrxL try incognito mode or use a different YT account, and see if things change.

I have no problems with the previous patch, so I guess further time it's needed to finalize this patch.

**Comment by 0xrxL** [comment]
> I'm asking because it might be new behavior that is account specific, and it could be useful to know.

The incognito spoof works, and other accounts that I have shows the same behavior with this new workaround (playback infinite loading).

**Comment by 0xrxL** [comment]
> Incognito spoof, meaning you turned on incognito mode in the app?
> 
> Or you mean the signature spoof that spoofs incognito mode (which is still present in this fix)?

I meant the second.

So the new workaround to restore history still needs of incognito signature spoofing to works?

**Comment by 0xrxL** [comment]
> The new workaround still uses the same incognito signature spoofing, but as I understand it [fixes](https://github.com/ReVanced/revanced-patches/blob/bcd8b48e70693dac1bfcc0bf4971d6b526065b59/src/main/kotlin/app/revanced/patches /youtube/misc/fix/playback/SpoofSignaturePatch.kt#L205-L209) an advertising related parameter that was confusing YT backend.

Well...this explains why it didn't work on my version of ReVanced (I removed the incognito spoof).

Thanks for the tip. 👍

**Comment by gp27** [comment]
I just patched YouTube v19.04.37 with the latest patches from 30 minutes ago and that should include the fix, but I am still experiencing the same issues with the history not being recorded (expect for shorts).

I applied all the patches, including including the client spoofing. I also got the latest alert from revanced which mentions the history issue when you open the patched app. 

Is there any information that I could share to help reproduce or debug the issue?

**Comment by oSumAtrIX** [comment]
Open a new issue.

**Comment by Rodriguezdavid203** [comment]
Here are the steps I took to fix the issue:

1. Downloaded YouTube version 19.04.37.
2. Opened ReVanced Manager and selected YouTube 19.04.37 in the storage option.
3. Confirmed the patch version 4.3.0 and then pressed "Patch."
4. Clicked on "install and update."

After reopening the patched YouTube, the watch history was working again. Hopefully, this solution works for you too.

**Comment by oSumAtrIX** [comment]
Reopening for a while to mitigate spam issues
