### ISSUE TITLE
bug: (TikTok) Feed Filter not Feed Filtering in Following tab

### ISSUE THREAD

**Issue by Mieridduryn** [ReVanced/revanced-patches#3246]
### Bug description

Error during use, patch not behaving as expected.

After patching TikTok 32.5.3 with Revanced-CLI 4.6.0 with Revanced Patches 4.7.0, and then installing the resulting APK, advertisements are not properly filtered out of my Following feed when using the app. They are labeled "sponsored." They should not be there.

Steps to reproduce:
1) Patch TikTok 32.5.3 (zhiliaoapp.musically) with Revanced CLI 4.6.0 and Revanced Patches 4.7.0. Revanced Integrations 1.8.0 was also used. I did not customize which patches were included, the defaults were fine for my needs.
Patches included in my own apk:
- Disable Login Requirement
- Downloads
- Feed Filter
- Fix Google Login
- Playback Speed
- Remember Clear Display
- Settings
- Show Seekbar
2) Patches will execute with no errors.
3) Install the resulting APK on an Android device.
4) Sign into TikTok.
5) Tap on "Following" and scroll.
6) Advertisements will appear.

For extra extra details, the device I patched the application on is running Linux Mint 21.3 Cinnamon and GNOME Terminal was used to run the patcher. The Android device I installed the patched application on is running Android 14 with OneUI 6.1.

Video of issue:
https://github.com/ReVanced/revanced-patches/assets/155842515/2f0d107c-371f-46ae-971e-ae4f41cda0c9

### Additional context

This issue has been reported before - #2632, where the issue was closed and a patch list + versions + video + steps to reproduce were requested. Please tell me what I can add to ensure that this issue is fixed if this information is insufficient.

#2534 reports the same issue and was closed for similar reasons.

I come bearing the necessary details so that hopefully, this issue can be solved once and for all.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Mieridduryn** [comment]
This also happens, on occasion, with viewing videos on someone's profile. It's just a lot less common there.

**Comment by oSumAtrIX** [comment]
Should be fixed with the linked PR. If not, reopen.

**Comment by Mieridduryn** [comment]
Problem persists after the update when viewing videos on someone's profile. Is this worth reopening this issue, or does it need a separate one?

**Comment by oSumAtrIX** [comment]
A new issue would be good

**Comment by Mieridduryn** [comment]
Actually... Nevermind, I have to ask that this issue be reopened, regardless.

TikTok 36.5.4, patched on Termux with Revancify this time. The exact same patches as I specified in my original post were applied here, as well. Revanced Patches 4.16.0, CLI 4.6.0, Patcher 20.0.0, Integrations 1.15.0. The issue hasn't popped up in a different area, it just hasn't been fully fixed. My bad.

**Comment by Mieridduryn** [comment]
https://github.com/user-attachments/assets/79ed5ebb-3f0d-41f5-b984-3b3146f8f73a
Screen recording of the ads still popping up in the Following feed.

**Comment by oSumAtrIX** [comment]
Unofficial tools are unsupported here

**Comment by Mieridduryn** [comment]
Is Revancify not simply a more convenient UI shell for ReVanced on Termux?

I guess I'll have to redo the patch job on my laptop at some point.

**Comment by vavsvirtual** [comment]
I sent @Mieridduryn an APK I patched myself that does not present the bug as described in following on my device but it still does on theirs.

Versions used: 
- revanced cli 4.6.0 
- patches 4.16.0
- integrations 1.15.0 
- com.zhiliaoapp.musically_36.5.4-2023605040_minAPI21(arm64-v8a,armeabi-v7a)

Patches applied:
- Disable login requirement
- Downloads
- Feed filter
- Fix Google login
- Playback speed
- Remember clear display
- Settings
- Show seekbar

Patching was done on Windows 11 in Powershell (Open JDK (21.0.3)) and completed with no errors. My device which is unable to replicate the bug is a Pixel 7 Pro on Android 15.

There's the potential this could be One UI related or even regional (I'm in UK, they're US) as we've experienced different behaviours with the same APK.

**Comment by Mieridduryn** [comment]
Confirming what Vav said. I asked her to do some testing with me and provide her input in this thread. We installed the exact same APK. I'm on OneUI 6.1, Android 14, but I'm not sure what she's on.

I am also experiencing, on the same app that she patched and sent over to me, ads playing after videos. Not fun!
