### ISSUE TITLE
bug(Instagram): Unable to Share music over Instagram Story

### ISSUE THREAD

**Issue by Radical4ever** [ReVanced/revanced-patches#55]
### Bug description

The issue is pretty straightfoward, its basically ReVanced/revanced-patches-template#2164 and it still persist on this new versions
Steps:
-press share button when playing a music
-select instagram
-nothing happens

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This has to be properly fixed in the GmsCore support patch instead

**Comment by Radical4ever** [comment]
> This has to be properly fixed in the GmsCore support patch instead

So i've updated the patches and repatched the apñ, but is still the same scenario as before

**Comment by Radical4ever** [comment]
Ok, so i've disabled certificate spoof for android auto to work and now i can share music over an ig story

**Comment by dhtzs** [comment]
Sharing on Instagram from patched YouTube Music aplication won't work for me either, yet it works normally when using the non-patched application.

OS: Android 13 (One UI 6.0)
Device: Galaxy S23
Youtube Music version: 6.40.52

**Comment by dhtzs** [comment]
Sharing on Instagram via patched YouTube Music aplication won't work for me either, yet it works normally when using the non-patched application.

OS: Android 13 (One UI 6.0)
Device: Galaxy S23
Youtube Music version: 6.40.52

**Comment by Radical4ever** [comment]
I guess i can close this since this issue has been fixed (for me)

**Comment by Kriscoart** [comment]
> Ok, so i've disabled certificate spoof for android auto to work and now i can share music over an ig story

how can i disable this feature in order to see if i can fix the same in mine? I have the same OS and hardware as yours so i hope it'll work on mine too, thanks!!

**Comment by oSumAtrIX** [comment]
It's a patch which can be selected in ReVanced Manager.
For support, move to one of our links at https://revanced.app.
