### ISSUE TITLE
bug(youtube/return-youtube-dislike): dislikes count disappears

### ISSUE THREAD

**Issue by Domiiniik** [ReVanced/revanced-patches#801]
### Type

Cosmetic

### Bug description

Dislikes count disappears if you enter short while watching a video  back out and scroll down recommended vids and back up.

### Steps to reproduce

Video reference on how to reproduce the issue down below.

### Relevant log output

```shell
-
```

### Screenshots or videos

https://github.com/revanced/revanced-patches/assets/30195961/2263ca0a-acb9-4042-94c6-acb9197d2b48

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
@Domiiniik should be fixed, reopen if not

**Comment by Domiiniik** [comment]
Still happens with new steps to follow, alongside a new bug that i just discovered with it that is: If you follow the steps that will cause dislikes to disappear after opening shorts and going back, you can no longer play or pause the video in PIP mode ( it shows a box with exclamation mark instead)  and when you go back to the video from PIP you can see dislikes are gone, video to reproduce:  (both issues included in the video)
@oSumAtrlX
https://github.com/ReVanced/revanced-patches/assets/30195961/6637b0df-239a-4336-bc00-a240f0bab612

**Comment by oSumAtrIX** [comment]
Are you using the latest version of patches?

**Comment by Domiiniik** [comment]
> Are you using the latest version of patches?

Yes, obviously, (Latest release ver)
